export const ERROR_MESSAGES = {
  internal: "internal error",
  nameRequired: "name is required",
  typeInvalid: "type must be food or drink",
  priceInvalid: "price must be a valid non-negative number",
  restaurantNotFound: "restaurant not found",
  menuItemNotFound: "menu item not found",
  fullNameRequired: "fullName is required",
  employeeNotFound: "employee not found",
  labelRequired: "label is required",
  deadlineInvalid: "deadline must be a valid date",
  foodRestaurantIdRequired: "foodRestaurantId is required",
  foodRestaurantTypeInvalid: "foodRestaurantId must reference a food restaurant",
  drinkRestaurantIdInvalid: "drinkRestaurantId must be a valid restaurant id",
  drinkRestaurantTypeInvalid: "drinkRestaurantId must reference a drink restaurant",
  roundNotFound: "round not found",
} as const;
