export const ERROR_MESSAGES = {
  internal: "internal error",
  nameRequired: "name is required",
  typeInvalid: "type must be food or drink",
  priceInvalid: "price must be a valid non-negative number",
  restaurantNotFound: "restaurant not found",
  menuItemNotFound: "menu item not found",
  fullNameRequired: "fullName is required",
  employeeNotFound: "employee not found",
  labelRequired: "label is required",
  deadlineInvalid: "deadline must be a valid date",
  foodRestaurantIdRequired: "foodRestaurantId is required",
  foodRestaurantTypeInvalid: "foodRestaurantId must reference a food restaurant",
  drinkRestaurantIdInvalid: "drinkRestaurantId must be a valid restaurant id",
  drinkRestaurantTypeInvalid: "drinkRestaurantId must reference a drink restaurant",
  roundNotFound: "round not found",
  menuItemIdRequired: "menuItemId is required",
  roundMenuItemMismatch: "menuItemId must belong to the round's food or drink restaurant",
  roundMenuItemAlreadyCurated: "menu item is already curated for this round",
  roundMenuItemNotFound: "round menu item not found",
  roundStatusInvalid: "status must be open, closed, or draft",
  roundOpenNoFoodItems: "round must have at least one curated food item to open",
  roundOpenAnotherOpen: "another round is already open",
  roundCloseNotOpen: "round is not open",
  roundRevertNotOpen: "round is not open",
  roundDeleteNotDraft: "round is not draft",
  roundEditNotDraft: "round is not draft",
  employeeIdRequired: "employeeId is required",
  foodRoundMenuItemIdRequired: "foodRoundMenuItemId is required",
  drinkRoundMenuItemIdInvalid: "drinkRoundMenuItemId must be a valid round menu item id",
  roundNotOpenForSubmission: "round is not open",
  roundDeadlinePassed: "the deadline for this round has passed",
  foodRoundMenuItemInvalid: "foodRoundMenuItemId must belong to this round's food restaurant",
  drinkRoundMenuItemInvalid: "drinkRoundMenuItemId must belong to this round's drink restaurant",
  submissionNoDrinkRestaurant: "this round has no drink restaurant",
  menuImageRequired: "menuImage file is required",
  menuImageTypeInvalid: "menuImage must be a JPEG, PNG, or WebP image",
  menuImageTooLarge: "menuImage must be 10MB or smaller",
  menuImageNotFound: "this restaurant has no menu image",
} as const;
